# Introduction

- The purpose of this notebook is to demonstrate the various matrix decomposition methods

In [2]:
# the cell below is needed to enable equation numbering

In [3]:
%%javascript
MathJax.Hub.Config({
    TeX: { equationNumbers: { autoNumber: "AMS" } }
});

<IPython.core.display.Javascript object>

# SVD
- The notes for this section, with the exception of section 2.1, are mostly comprised of a lecture series given by Steve Brunton [SVD: Mathematical Overview](https://www.youtube.com/watch?v=nbBvuuNVfco)
- We'll first do a manual SVD calculation to refresh our memory from our introductory linear algebra class and then develop a more intuitive understanding

## SVD for 2x2 matrix
- [MIT: Computing the Singular Value Decomposition](https://www.youtube.com/watch?v=cOUTpqlX-Xs)

Let's compute the SVD for matrix $c$.
$$
\begin{equation}
    c = \begin{bmatrix} 
            5 & 5 \\ 
            -1 & 7
        \end{bmatrix} 
\end{equation}
$$

Recall, we are trying to set $c = U \Sigma V^T$. $U$ and $V$ are going to be orthogonal matrices (i.e. their columns are orthonormal sets), and $\Sigma$ is going to be a diagonal matrix. To begin solving this we're going to need two equations:
$$
\begin{equation}
    C^TC = V \Sigma^T \Sigma V^T \\
    CV = U \Sigma
\end{equation}
$$

**Step 1: solve for $C^TC$ first:**
$$
\begin{align}
    c^Tc &= \begin{bmatrix} 
            5 & -1 \\ 
            5 & 7
        \end{bmatrix} 
        \begin{bmatrix} 
            5 & 5 \\ 
            -1 & 7
        \end{bmatrix} \\
        &= \begin{bmatrix}
            26 & 18 \\
            18 & 74 
         \end{bmatrix}
\end{align}
$$

 **Step 2: find the eigenvalue of $c^Tc$**
$$
\begin{align}
    det(c^Tc - \lambda I) &= det \left(\begin{bmatrix}
            26- \lambda & 18\\
            18 & 74 - \lambda
         \end{bmatrix} \right) \\
         &= \lambda^2 - 100\lambda + 1600 \\
         &= (\lambda - 20) (\lambda-80) \\
         &\therefore \lambda_1 = 20, \, \lambda_2 = 80
\end{align}
$$

Now we need to find the eigenvectors for $\lambda = 80$ and $\lambda = 20$. Remember, by convention, we always do the most significant lambda value first - that way it appears as the first column in the matrix $v$.

**Step 3: find the eigenvectors corresponding to the eigenvalue of $\lambda = 80$**  
Subtract $\lambda = 80$ from the diagonal entries.
$$
\begin{align}
    c^Tc - 80\lambda I &= \left(\begin{bmatrix}
            -54 & 18 \\
            18 & -6 
         \end{bmatrix} \right) \\
\end{align}
$$
Let's reduce this matrix to find $v_1$.  If we do the following transformations: $R_1 \rightarrow R_1 / -54$ and then $R_2 \rightarrow R_2 - 18R_1$ we'll end up with the following:
$$
\begin{align}
    \begin{bmatrix}
        1 & -0.33 \\
        0 & 0
    \end{bmatrix}
\end{align}
$$
Multiplying that matrix by the vector $\left[ x_1, x_2 \right]^T$ we'll end up with $x_1 - 0.33 x_2 = 0$ which implies $x_1 = 0.33x_2$. Therefore, by letting $x_2 = 1$, we have:
$$
\begin{align}
    v = \begin{bmatrix}
            0.33 \\
            1
        \end{bmatrix}
\end{align}
$$

**Step 4: find the eigenvectors corresponding to the eigenvalue of $\lambda = 20$**  
Subtract $\lambda = 80$ from the diagonal entries.

$$
\begin{align}
c^Tc - 20I = \begin{bmatrix}
            6 & 18 \\
            18 & 54
         \end{bmatrix} 
\end{align}
$$
Let's reduce this matrix to find $v_2$.  If we do the following transformations: $R_1 \rightarrow R_1 / 18$ and then $R_2 \rightarrow R_2 - 6R_1$ we'll end up with the following:

$$
\begin{align}
c^Tc - 20I = \begin{bmatrix}
            1 & 3 \\
            0 & 0
         \end{bmatrix} 
\end{align}
$$
Multiplying that matrix by the vector $\left[ x_1, x_2 \right]^T$ we'll end up with $x_1+ 3x_2 = 0$ which implies $x_1 = -3x_2$. Therefore, by letting $x_2 = 1$, we have:
$$
\begin{align}
    v = \begin{bmatrix}
            -3 \\
            1
        \end{bmatrix}
\end{align}
$$

**Step 5: Normalize $v_1$ and $v_2$**  
For $v_1$ we have:
$$
\begin{align}
    Length \; L = \sqrt{0.33^2 + 1^2} = 1.05 \\
    v_1 = \left(\frac{0.33}{1.05}, \frac{1}{1.05}\right) = (0.32, 0.95)
\end{align}
$$

And for $v_2$ we have:
$$
\begin{align}
    Length \; L = \sqrt{-3^2 + 1^2} = 3.16\\
    v_2 = \left(\frac{-3}{3.16}, \frac{1}{3.16}\right) = (-0.95, 0.32)
\end{align}
$$

**Step 6: We have matrices $\Sigma$ and $U$**  
$$
\begin{align}
    \Sigma = \begin{bmatrix}
            \sqrt{80} & 0 \\
            0 & \sqrt{20}
        \end{bmatrix} = 
        \begin{bmatrix}
            8.94 & 0 \\
            0 & 4.47
        \end{bmatrix} \\
\end{align}
$$
$$
\begin{align}
    v = [v_1, v_2] =  \begin{bmatrix}
                                0.32 & -0.795 \\
                                0.95 & 0.32
                             \end{bmatrix}
\end{align}
$$

**Step 7: Find $U$ via the following formula: $\dfrac{1}{\sigma_i}A \,v_i$**
$$
\begin{align}
U = \dfrac{1}{\sigma_i}A \,v_i &= \dfrac{1}{80} \, 
                                    \begin{bmatrix} 
                                        5 & 5 \\ 
                                        -1 & 7
                                    \end{bmatrix} 
                                     \begin{bmatrix}
                                        0.32 & -0.95 \\
                                        0.95 & 0.32
                                     \end{bmatrix} \\
                           &= \begin{bmatrix}
                                   0.71 & -0.71 \\
                                   0.71 & 0.71
                              \end{bmatrix}                              
\end{align}
$$

**Step 8: Confirm that $U = (U*\Sigma) * V^T$**
- We'll confirm this with numpy in the step below

In [1]:
# confirm the solution above
u = [[1/np.sqrt(2), -1/np.sqrt(2)], [1/np.sqrt(2), 1/ np.sqrt(2)]]
sigma = [[np.sqrt(80),0],[0, np.sqrt(20)]]
v = [[0.32, 0.95], [-0.95, 0.32]] # note it's V^T

In [2]:
temp = np.matmul(u,sigma)
np.matmul(temp, v)

array([[ 5.02802148,  4.9963987 ],
       [-0.98030607,  7.02025641]])

## Solving SVD with numpy
- Notice, the results match what we calculated above

In [639]:
c = [[5,5],[-1,7]]
u, s, vh = np.linalg.svd(c,full_matrices=True)
s = [[8.94,0],[0,4.47]] # Need to redefine s because np.linalg only provides the eigenvalues (not the full matrix)

temp = np.matmul(u,s) # create temp matrix
np.matmul(temp,vh)

array([[5.00, 5.00],
       [-1.00, 7.00]])

In [640]:
print(u, "\n \n", s, "\n \n", vh)

[[0.71 0.71]
 [0.71 -0.71]] 
 
 [[8.94, 0], [0, 4.47]] 
 
 [[0.32 0.95]
 [0.95 -0.32]]


## SVD: Introduction

The $SVD$ for says that for any matrix $A$,
$$\begin{equation}
A = U \Sigma V^T
\end{equation}$$
where $U$ and $V$ are orthogonal matrices and $\Sigma$ is a diagonal matrix. 
If $A$ is an invertible matrix then we can use its $SVD$ to find $A^{-1}$:
$$\begin{equation}
A^{-1} = V\Sigma^{-1}U^*
\end{equation}$$

Let's briefly review some reasons why we care about $SVD$:  
- SVD works on non-square matrices
- SVD is used in principal components analysis (PCA)
- Where is it used? Google page rank algorithm, facial recognition technology, recommender systems (e.g. Netflix, Amazon)
- Why is it so popular? The SVD is based on simple, interpretable linear algebra

Now, let's review some properties and features of the $SVD$:
- SVD is guaranteed to exist and it is unique
- The $U$ and $V$ matrix are orthogonal (i.e. unitary matrices), and the $\Sigma$ matrix is diagonal
- "The columns of U are the left singular vectors; S (the same dimensions as A) has singular values and is diagonal (mode amplitudes); and VT has rows that are the right singular vectors. The SVD represents an expansion of the original data in a coordinate system where the covariance matrix is diagonal." - [MIT: SVD tutorial](https://web.mit.edu/be.400/www/SVD/Singular_Value_Decomposition.htm)

Let's review some key features about each individual matrix. Recall, the advantage of $SVD$ is that it is has intuitive and physical interpretations.
- $U$ Matrix  
    - Unitary matrix
    - $UU^T = U^TU = I_{n x n}$
    - This is called the left-singular vector  
    - **Interpretation:**
    

- $\Sigma$ Matrix  
    - Diagonal matrix with the same shape as $X$ matrix
    - $\sigma_1 \ge \sigma_2 \ge \sigma_3 \ge ... \ge \sigma_m \ge 0$
        - This means each column of eigenvectors is "more important" than the column to the right. In other words, each column of $\Sigma$ provides a basis in which we can represent $X$
    - This is called a matrix of singular values  
    - **Interpretation:** the columns are hierarchically organized in order of importance 


- $V$ Matrix  
    - Unitary matrix
    - $VV^T = V^TV = I_{m x m}$
    - This is called the right-singular vector  
    - **Interpretation:** This is best explained via example.  In the case of facial recognition (e.g. EigenFaces), the first column of $V^T$ is the mixture of all the faces from matrix $U$ that is needed to equal to equal the first column of $X$
    

## Notes from [Singular Value Decomposition (SVD): Dominant Correlations](https://www.youtube.com/watch?v=WmDnaoY2Ivs)

- A key interpretation is the following: We can think of $U$ and $V^T$ as eigenvectors of a correlation matrix given by $XX^T$ or $X^TX$
- The methodology outlined below is not a very efficient or accurate way to calculate the SVD; however, it provides an intuitive understanding of the SVD matrix

**Correlation Matrix**  
Let's assume that matrix $X$ is a tall skinny matrix. In the eigenfaces example, each column would represent a face.  Now, let's look at the underlying math:
$$
\begin{align*}
X^TX &=  \begin{bmatrix} 
            \ldots & x_1^T & \ldots \\ 
            \ldots & x_2^T & \ldots \\ 
        \end{bmatrix} 
        \begin{bmatrix} 
            \vdots & \vdots  & \vdots \\ 
             x_1 & x_2 & x_3 \\ 
            \vdots & \vdots  & \vdots \\ 
            \vdots & \vdots  & \vdots \\ 
        \end{bmatrix} \\
         &= \begin{bmatrix} 
            x_1^Tx_2 & x_1^Tx_2 & \ldots & x_1^Tx_m \\
            x_2^Tx_2 & x_2^Tx_2 & \ldots & x_2^Tx_m \\
            \vdots & \vdots & \ddots & \vdots \\
            x_m^Tx_2 & x_m^Tx_2 & \ldots & x_m^Tx_m \\
        \end{bmatrix}
\end{align*}
$$

This new matrix is the correlation matrix. 

Let's examine what each entry of this new matrix, $X^TX$, represents. Each entry in the new matrix is an inner product between the two matrices.  More specifically, we can write: $x_i^Tx_j = <x_i, x_j>$. Applying basic properties of inner products, we know that if the inner product between two faces is close to zero then the two faces are dissimilar, and if two faces have a large value then the two faces share a lot of features. 

Let's look further into what this new matrix represents. Recall,
$$
\begin{equation}
    X=U \Sigma V^T \\
    X^T = V \Sigma U^T
\end{equation}
$$

Multiplying $X^TX$ we receive:
$$ 
\begin{align}
    X^TX &= V \Sigma U^T U \Sigma V^T \\
    &= V \Sigma^2 V^T
\end{align}
$$ where we applied the following fact $U^T U = I $.

Note, equation 3 is eigenvalue decomposition for the matrix $X^TX$.  Let's multiply the LHS of equation 2 and equation 3 by $V$ to cancel out the $V^T$.
$$
\begin{equation}
X^TXV = V \Sigma^2 
\end{equation}
$$

Now, the $\Sigma^2$ values are the eigenvalues and the $V$ term is the eigenvectors of the correlation matrix (i.e. $X^TX$).
Next steps: We're going to compute $U, \Sigma, V$ as the eigenvalues and eigenvectors of the correlation matrix. 

# LU Decomposition

# QR Decomposition

# Cholesky decomposition